In [7]:
import numpy as np

# Creating array from list with type float
a = np.array([[1, 2, 3],
                [4, 5, 6]],  dtype = 'float')
print(a)
print(type(a), end = '\n\n' )

# Return a new array with random-values
b = np.empty(4, dtype = 'int')
c = np.empty([4,5], dtype = 'float')
print(b)
print(c, end = '\n\n')

# Return a new aray where all elements have the same value:
h = np.full([3, 4], 8)
print(h)
# Return a new array with zeros, or ones,...
d = np.ones([2, 5], dtype = 'int')
print(d, end = '\n\n')

# Return an array like range():[start, stop)
print(np.arange(4, 19, 3, dtype = 'float'), end = '\n\n')
print(np.arange(1, 3.2, 0.3))

# Reshape an array without change data of array, 
print(np.arange(2, 25, 2).reshape(3, 4))        # Must: (24 - 2)/12 = 3 x 4
print(np.arange(2, 25, 2).reshape(1, 12))


# Return a copy of array with it's collapsed into 1 dimension (use 'copy' for normal):
e = np.array([[5, 7, 9], [11, 14, 56], [55, 4, 119]])
print(e.flatten(), end = '\n\n')

# Return a array nxn like identify matrix
f = np.identity(6)
print(f, end = '\n\n')

             
# Transform array into lower, upper triangle ; extract a diagonal
g = np.array([[1, 2, 3], [4, 10, 6], [7, 8, 100]])
print(np.diag(g))

up_tri = np.triu(g, k = 1)      # Change k to change values 0 in matrix
print(up_tri)

low_tri = np.tril(g, k = 0)
print(low_tri)




[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>

[ 1226314878   820166555  1988816179 -1622389095]
[[7.73647091e-312 7.73647020e-312 7.73647020e-312 7.73647020e-312
  7.73647020e-312]
 [7.73647020e-312 7.73647019e-312 7.73647019e-312 7.73647019e-312
  7.73647019e-312]
 [7.73647019e-312 7.73647019e-312 7.73647019e-312 2.44040351e+204
  3.60241447e+252]
 [6.06003397e+233 2.87244893e+161 2.19961423e-094 1.50008929e+248
  5.88203343e+294]]

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
[[1 1 1 1 1]
 [1 1 1 1 1]]

[ 4.  7. 10. 13. 16.]

[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[ 2  4  6  8 10 12 14 16 18 20 22 24]]
[  5   7   9  11  14  56  55   4 119]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[  1  10 100]
[[0 2 3]
 [0 0 6]
 [0 0 0]]
[[  1   0   0]
 [  4  10   0]
 [  7   8 100]]


Tạo vector: ta coi vector là 1 mảng 1-D

In [1]:
import numpy as np

list1 = [1, 2, 3]
list2 = [10, 11, 12]

vector1 = np.array(list1)
vector2 = np.array(list2)
print(vector1)
# Basic calculate:
print(vector1*vector2)

# Dot product: tích vô hướng
print(vector1.dot(vector2))     

# Cross product: tích có hướng, hàm chỉ làm việc với vector 3 chiều, nếu nhập ít hơn, tự động thêm 0 để thành 3 chiều
print(np.cross(vector1, vector2))



[1 2 3]
[10 22 36]
68
[-9 18 -9]


Tiếp tục các thao tác cơ bản với array:

In [27]:
import numpy as np

# Append values of the n-dimensional array: kích thước của 2 mảng phải khớp nhau
# axis = 0: ta thêm để tăng số dòng, axis = 1 để tăng số cột
a = np.arange(1, 13).reshape(2, 6)
append_row = np.arange(12, 18).reshape(1, 6)
a1 = np.append(a, append_row, axis = 0)

append_col = np.zeros(3).reshape(3, 1)
a2 = np.append(a1, append_col, axis = 1)
print(a2, end = '\n\n')


# Swap columns:
swap_array = np.arange(16).reshape(4, 4)
swap_array[:, [1, 3]] = swap_array[:, [3, 1]]
print(swap_array, end = '\n\n')


# Joining arrays along a axis:
array1 = np.array([[1, 2], [5, 6]])
array2 = np.array([[3, 4], [7, 8]])
new_array = np.concatenate((array1, array2), axis = 0)
print(new_array)


# Find union of two 1-dimensional arrays:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([10, 30, 50, 80])
print(np.union1d(arr1, arr2), end = '\n\n')


# Tìm các phần tử phân biệt có trong array
b = np.array([[11, 12, 12, 11, 12],
                [13, 11, 12, 11, 12],
                [10, 9, 15, 17, 15],
                [8, 9, 11, 12, 11]])
print(np.unique(b))
# Thêm axis để tìm các hàng(cột) phân biệt: dòng là 0, cột là 1
print(np.unique(b, axis = 1), end = '\n\n')


# Các thao tác cộng, trừ, nhân (ai.bi), chia (ai/bi):
x = np.array([[1, 2, 5], [3, 4, 7], [3, 3, 3]])
y = np.array([[4, 8, 10], [6, 8, 14], [3, 3, 3]])
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

# Nhân 2 ma trận:
print(np.dot(x, y))

# Tính tổng các phần tử theo hàng(cột):
print(np.sum(x, axis = 0 ))

# Ma trận chuyển vị:
print(np.array(x).T, end = '\n\n')

# Tính giá trị riêng của ma trận:
GTR = np.linalg.eigvals([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(GTR)

# Tính định thức của ma trận:
determinant_matrix = np.linalg.det([[1, 2, 4], [2, 4, 8], [5, -4, 5]])
print(determinant_matrix)

# Nghịch đảo của ma trận: chỉ sử dụng được khi ma trận có nghịch đảo
arr = np.array([[1, 2, 3], [0, 1, 0], [1, 0, 4]])
inverse_arr = np.linalg.inv(arr)
print(inverse_arr, end = '\n\n')

matrix = np.array([[6, 1, 1],
                    [4, -5, 6],
                    [12, -6, 4]])
print(np.linalg.matrix_rank(matrix))                        # Rank ma trận
print(np.trace(matrix))                                     # Trace ma trận

print(np.linalg.matrix_power(matrix, 3), end = '\n\n')         # Tính A^n

# Giải phương trình ma trận Ax = b:
A = np.array([[1, 2, 3], [4, 6, 3], [2, 7, 8]])
b = np.array([4, 6, 23])
print(np.linalg.solve(A, b))

# Tìm xấp xỉ ma trận trực giao Q, ma trận tam giác trên R sao cho A = QR:
Q, R = np.linalg.qr(A)
print("Q =\n", Q, "\nR = \n", R, '\n')

# Tính chuẩn của ma trận:
""" Chuẩn 1: tính max của các cột
    Chuẩn vô cùng: tính max của các hàng
    Chuẩn 2: lấy max căn bậc 2 của giá trị riêng ma trận A.A^T
"""
print(np.linalg.norm(A, 2))

# Cắt lấy ma trận nhỏ hơn:
cut_matrix = np.array([[1, 2, 4], [2, 3, 6], [4, 5, 88], [4, 76, 45]])
print(np.compress([1, 0, 2, 0], cut_matrix, axis = 0))          # Nghĩa là hàng 1 và 3 được chọn, và cắt theo hàng
print(np.compress([2, 0, 1, 0], cut_matrix, axis = 1))          # Cắt theo cột



[[ 1.  2.  3.  4.  5.  6.  0.]
 [ 7.  8.  9. 10. 11. 12.  0.]
 [12. 13. 14. 15. 16. 17.  0.]]

[[ 0  3  2  1]
 [ 4  7  6  5]
 [ 8 11 10  9]
 [12 15 14 13]]

[[1 2]
 [5 6]
 [3 4]
 [7 8]]
[10 20 30 40 50 80]

[ 8  9 10 11 12 13 15 17]
[[11 11 12 12]
 [11 13 11 12]
 [17 10  9 15]
 [12  8  9 11]]

[[ 5 10 15]
 [ 9 12 21]
 [ 6  6  6]]
[[-3 -6 -5]
 [-3 -4 -7]
 [ 0  0  0]]
[[ 4 16 50]
 [18 32 98]
 [ 9  9  9]]
[[0.25 0.25 0.5 ]
 [0.5  0.5  0.5 ]
 [1.   1.   1.  ]]
[[ 31  39  53]
 [ 57  77 107]
 [ 39  57  81]]
[ 7  9 15]
[[1 3 3]
 [2 4 3]
 [5 7 3]]

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
0.0
[[ 4. -8. -3.]
 [-0.  1. -0.]
 [-1.  2.  1.]]

3
5
[[484 -19  86]
 [404 123  26]
 [552  54 172]]

[-6.  5.  0.]
Q =
 [[-0.21821789  0.02660996 -0.97553722]
 [-0.87287156 -0.45236931  0.18291323]
 [-0.43643578  0.89143363  0.12194215]] 
R = 
 [[-4.58257569 -8.72871561 -6.7647546 ]
 [ 0.          3.57903951  5.85419102]
 [ 0.          0.         -1.40233475]] 

13.467994032758847
[[ 1  2  4]
 [ 4  

Các hàm toán học trong Numpy:

In [8]:
# Các hàm lượng giác:
import numpy as np
import math
sin_array = [0, math.pi/2, math.pi/3]
print(np.sin(sin_array))                # Trả về sin(ptu trong mảng)
print(np.rad2deg(sin_array))
""" Ngoài ra còn có các hàm lượng giác khác như cos, tan, arcsin, arccos, arctan,
các hàm chuyển đổi độ <-> radian,..."""

# Các hàm hyperbolic:
hyper_array = [0, 1, math.pi/2, 4]
print(np.sinh(hyper_array), end = '\n\n')             # Tương tự có các hàm cosh, tanh, arc,...

# Hàm làm tròn số thập phân, đến mấy chữ số:
array = [0.5538, 1.44546, 4.5454, 434.65777]
round_array = np.around(array, decimals = 3)
print(round_array)

# Hàm trả về phần nguyên trên, nguyên dưới của 1 số:
print(np.ceil([6.565, 4.656, -5.656]))
print(np.floor([6.565, 4.656, -5.656]), end = '\n\n')


# Hàm số mũ, logarit, gcd:
print(np.exp([1, 3, 5, 12, 22]))        # Trả về giá trị e^(ptu)
print(np.log([1, 3, 5, 12, 22]))        # Trả về giá trị ln
print(np.log2([1, 3, 5, 12, 22]))
print(np.gcd([1, 4, 35, 55, 97], [4, 6, 65, 11, 65]), end = '\n\n')


# Các hàm tính toán: cơ bản(đã trình bày), mod, thương và số dư, mũ, căn...
arr1 = [2, 27, 1, 8, 9, 2.25]
arr2 = [1, -3, 5, -64, 80, -1.5]
print(np.mod(arr2, arr1))
print(np.divmod(arr2, arr1))            # Trả về 2 mảng thương và số dư
print(np.fabs(arr2), end = '\n\n') 


# Hàm clip: giới hạn các giá trị trong khoảng (a, b):
in_array = [1, 2, 4, 6, 66, 34, 44, 5]
print(np.clip(in_array, 4, 34))
print(np.maximum(in_array, 30))          # Số nào nhỏ hơn 30 sẽ bằng 30
print(np.minimum(in_array, 5))           # Số nào lớn hơn 5 sẽ bằng 5


[0.        1.        0.8660254]
[ 0. 90. 60.]
[ 0.          1.17520119  2.3012989  27.2899172 ]

[  0.554   1.445   4.545 434.658]
[ 7.  5. -5.]
[ 6.  4. -6.]

[2.71828183e+00 2.00855369e+01 1.48413159e+02 1.62754791e+05
 3.58491285e+09]
[0.         1.09861229 1.60943791 2.48490665 3.09104245]
[0.         1.5849625  2.32192809 3.5849625  4.45943162]
[ 1  2  5 11  1]

[ 1.   24.    0.    0.    8.    0.75]
(array([ 0., -1.,  5., -8.,  8., -1.]), array([ 1.  , 24.  ,  0.  ,  0.  ,  8.  ,  0.75]))
[ 1.   3.   5.  64.  80.   1.5]

[ 4  4  4  6 34 34 34  5]
[30 30 30 30 66 34 44 30]
[1 2 4 5 5 5 5 5]


String trong numpy: 

In [5]:
import numpy as np
# Trả về chuỗi thường, chuỗi in hoa:
print(np.char.lower(['My name is VHoang']))
print(np.char.upper(['My name is VHoang']))

# Hàm split, hàm join đã biết

# Hàm trả về số lần xuất hiện của string con trong string:
a = np.array(['Misissy', 'name', 'is the most of is', 'is VCH', 'His', 'C'])
print(np.char.count(a, 'is'))

# Hàm return True nếu các kí tự trong string đều là số:
print(np.char.isnumeric('123434oi5'))

# Trả về vị trí xuất hiện đầu tiên, cuối cùng của chuỗi con trong chuỗi:
print(np.char.index('4555343abfba', 'a'))
print(np.char.rindex('4555343abfba', 'a'))

# Còn các hàm như so sánh, kiểm tra tính thập phân, in thường, in hoa,...


['my name is vhoang']
['MY NAME IS VHOANG']
[2 0 2 1 1 0]
False
7
11


Hàm liên quan đến xác suất, đại số tuyến tính, ma trận(tiếp): 

In [28]:
import numpy as np 
array = [2, 4, 5, 6, 54, 545]
print(np.var(array))                 # Phương sai
print(np.std(array))                 # Độ lệch chuẩn
print(np.mean(array))                # Tính trung bình
print(np.median(array))              # Trả về trung vị



39463.22222222222
198.653523055148
102.66666666666667


Tìm kiếm, sắp xếp trong array:

In [44]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45]) 
print(np.where(arr%3 == 0, arr, 10*arr))    # Trả về arr, phần tử ko chia hết cho 3, thì phải nhân 10
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
print(np.where(a < 4, a, -1))               # Trả về mảng, phần tử nào => 4 thì cho bằng -1
print(np.sort(arr))                         # Sắp xếp theo thứ tự tăng dần

print(np.argsort(arr))                      # Trả về dãy chỉ số các phần tử khi được sắp xếp
print(np.argmax(arr))                       # Trả về chỉ số của phần tử lớn nhất trong mảng


[100 320  30 500 200 820 910  45]
[[ 0  1  2]
 [ 0  2 -1]
 [ 0  3 -1]]
[10 20 30 32 45 50 82 91]
[0 4 2 1 7 3 5 6]
